format = """\
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$line_break\
$character\
"""

[username]
show_always = true
style_user = "bold blue"
format = "[$user]($style)"

[hostname]
ssh_only = true
style = "bold green"
format = " on [$hostname]($style)"

[directory]
truncation_length = 8
style = "bold yellow"
format = " in [$path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = ""
style = "bold purple"

[git_commit]
style = "bold cyan"

[character]
success_symbol = "[❯](bold white)"
error_symbol = "[❯](bold red)"
