export ZSH=$HOME/.dotfiles/ohmyzsh

ZSH_CUSTOM=$HOME/.dotfiles/zsh
ZSH_CACHE_DIR=$ZSH_CUSTOM/cache

DISABLE_AUTO_UPDATE="true"

plugins=(
    zsh-autopair
    zsh-autosuggestions
    zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

eval "$(~/.dotfiles/bin/starship init zsh)"
