export ZSH=$HOME/.dotfiles/ohmyzsh

ZSH_CUSTOM=$HOME/.dotfiles/zsh
ZSH_CACHE_DIR=$ZSH_CUSTOM/cache

if [ -f $ZSH_CUSTOM/zshrc_before_local ]; then
    source $ZSH_CUSTOM/zshrc_before_local
fi

DISABLE_AUTO_UPDATE="true"

plugins=(
    colored-man-pages
    zsh-autopair
    zsh-autosuggestions
    zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

# Allow local customizations
if [ -f $ZSH_CUSTOM/zshrc_local ]; then
    source $ZSH_CUSTOM/zshrc_local
fi

eval "$($HOME/bin/starship init zsh)"
