#!/bin/bash

# .bashrc - load all of the dotfiles

# Do not do anything if it's a non interactive shell.
[ -z "$PS1" ] && return

USE_ZSH=false

# Prioritize local zsh installation.
if [ -x "$HOME/bin/zsh" ]; then
    USE_ZSH=true
    export SHELL="$HOME/bin/zsh"
# Else use the system installation.
elif which zsh &> /dev/null && [ -x "$(which zsh)" ]; then
    USE_ZSH=true
    export SHELL="$(which zsh)"
fi

if [ "$USE_ZSH" = true ]; then
    if [[ -o login ]]; then
        exec "$SHELL" -l
    else
        exec "$SHELL"
    fi
# If zsh is not present, resume using bash.
else
    load_dotfiles() {
        declare -a files=(
            $HOME/.dotfiles/bash/bash_aliases
            $HOME/.dotfiles/bash/bash_exports
            $HOME/.dotfiles/bash/bash_local
            $HOME/.dotfiles/bash/bash_paths
            $HOME/.dotfiles/bash/bash_prompt
            $HOME/.dotfiles/bash/bash_options
        )

        # if these files are readable, source them
        for index in ${!files[*]}
        do
            if [[ -r ${files[$index]} ]]; then
                source ${files[$index]}
            fi
        done
    }

    load_dotfiles
    unset load_dotfiles
fi
